version: 2

updates:
  # Keep GitHub Actions up to date
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "main"
    labels:
      - "dependencies"
      - "github-actions"
    commit-message:
      prefix: "ci"
    groups:
      actions-all:
        patterns:
          - "*"
    open-pull-requests-limit: 10

  # Keep Docker images up to date (qodana-configuration-uploader)
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "main"
    labels:
      - "dependencies"
      - "docker"
    commit-message:
      prefix: "build(docker)"
    open-pull-requests-limit: 5
